name: CI/CD Pipeline

on:
  push:
    branches:
      - master         # Trigger when changes are pushed to the master branch
  pull_request:
    branches:
      - master         # Trigger when a pull request targets the master branch

permissions:
  contents: read

jobs:
   # --- Build Job ---
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v4 # Clone the repository

      - name: Set up Python 3.10
        uses: actions/setup-python@v3   # Set up the Python environment
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest   
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi


  test:
    name: Test
    runs-on: ubuntu-latest
    needs: build     # This job runs only after the build job succeeds
    steps:
      - name: Check out code
        uses: actions/checkout@v4   # Clone the repository again

      - name: Set up Python 3.10
        uses: actions/setup-python@v3   # Set up the Python environment
        with:
          python-version: '3.10'

      # Run flake8 to catch syntax errors and undefined names.
      # Run flake8 in exit-zero mode to show warnings without failing the build.
      - name: Run Linting
        run: |
         flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
         flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Run Tests
        run: pytest

 # --- Deploy Job ---
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: test   # This job runs only after the test job succeeds
    # This condition ensures that deploy only runs on pushes to master (not on PRs).
    if: github.ref == 'refs/heads/master' && github.event_name == 'push'
    steps:
      - name: Check out code
        uses: actions/checkout@v4  # Clone the repository

      - name: Deploy to Production
        run: |
          echo "Deploying your app..."

        # commands to deploy to railway